image: alpine:latest    # Ideally, a dedicated docker image with Truffle on it

before_script:
 - apk add --no-cache nodejs nodejs-npm git python g++ make
 - npm install -g truffle ethereumjs-testrpc

stages:
 - build
 - test
 - deploy

build:
 stage: build
 tags: [ek-docker]
 script:
   - truffle compile

test:
 stage: test
 tags: [ek-docker]
 script:
   - testrpc -p 8242 &     # We could also have a service
   - truffle test

deploy:
 stage: deploy
 tags: [ek-docker]
 script:
   - testrpc -p 8242 &
   - truffle migrate --network ethdev
